name: Checks
run-name: Checks, branch:${{ github.ref_name }}, triggered by @${{ github.actor }}

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:

concurrency:
  # Run only for most recent commit in PRs but for all tags and commits on main
  # Ref: https://docs.github.com/en/actions/using-jobs/using-concurrency
  group: ${{ github.workflow }}-${{ github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
      # Needed by Netlify to add a comment to the PR
      issues: write
      pull-requests: write
      deployments: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - name: Set Hugo cache directory
        run: echo "HUGO_CACHEDIR=${{ runner.temp }}/hugo_cache" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/cache@v4
        with:
          path: ${{ env.HUGO_CACHEDIR }}
          key: ${{ runner.os }}-hugomod-${{ hashFiles('content/***') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      - uses: jdx/mise-action@v2
        with:
          install: false

      - name: Build with Hugo
        run: make build

      - uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          identity_url: https://identity.bitwarden.eu
          api_url: https://api.bitwarden.eu
          secrets: |
            c13526c8-8345-4d33-b60a-b2470153f2e8 > NETLIFY_AUTH_TOKEN 
            331ea4ce-da95-4917-b37e-b24701564694 > NETLIFY_SITE_ID

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './public'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions: PR ${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}"
          enable-pull-request-comment: true
          overwrites-pull-request-comment: true
          enable-commit-comment: false
          fails-without-credentials: true
          alias: ${{ github.event.pull_request.number }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ env.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ env.NETLIFY_SITE_ID }}
        timeout-minutes: 1
